:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

= Build a Native Java REST API with Helidon and OAuth 2.0

In this demo, I'll show how to create a secure REST API and native image with Helidon. You'll see how to run a secure, OAuth 2.0-protected, Java REST API that allows JWT authentication. Then, I'll compare its performance with Micronaut, Quarkus, and Spring Boot.

**Prerequisites:**

- https://sdkman.io/[SDKMAN] (for Java 17 with GraalVM)
- https://httpie.io/[HTTPie] (a better version of cURL)
- An https://developer.okta.com[Okta Developer] Account (or the https://cli.okta.com/[Okta CLI])

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

== Install a JDK with GraalVM

. Use SDKMAN to install Java 17 with GraalVM

  sdk install java 22.0.0.2.r17-grl

. Add the native extension to the JDK:

  gu install native-image

== Generate an OAuth 2.0 Access Token

. Install the https://cli.okta.com/[Okta CLI] and run `okta register` to sign up for a new account. If you already have an account, run `okta login`.

. Run `okta apps create`. Set `oidcdebugger` as an app name, choose **Single-Page App** and press **Enter**.

. Use `\https://oidcdebugger.com/debug` for the Redirect URI and set the Logout Redirect URI to `\https://oidcdebugger.com`.

. Navigate to the https://oidcdebugger.com/[OpenID Connect Debugger] website. Fill in your client ID, and use `\https://{yourOktaDomain}/oauth2/default/v1/authorize` for the Authorize URI. The `state` field must be filled but can contain any characters. Select **token** for the response type.

. Click **Send Request** to continue.

. Set it as a `TOKEN` environment variable in a terminal window.

  TOKEN=eyJraWQiOiJYa2pXdjMzTDRBYU1ZSzNGM...

== Construct a Java API with Helidon

. Create a Helidon app with OAuth 2.0 support:
+
[source,shell]
----
mvn -U archetype:generate -DinteractiveMode=false \
   -DarchetypeGroupId=io.helidon.archetypes \
   -DarchetypeArtifactId=helidon-quickstart-mp \
   -DarchetypeVersion=2.4.2 \
   -DgroupId=com.okta.rest \
   -DartifactId=helidon \
   -Dpackage=com.okta.rest
----
+
TIP: You can also install the https://helidon.io/docs/v2/#/about/05_cli[Helidon's CLI] and run `helidon init`.

. Add MicroProfile JWT support in `pom.xml`:
+
[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.jwt</groupId>
    <artifactId>helidon-microprofile-jwt-auth</artifactId>
</dependency>
----

. Add a `HelloController` class that returns the user's information: [`h-hello`]
+
[source,java]
----
package com.okta.rest.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
public class HelloController {

    @GetMapping("/hello")
    public String hello(Principal principal) {
        return "Hello, " + principal.getName() + "!";
    }

}
----

. Add your Okta endpoints to `src/main/resources/META-INF/microprofile-config.properties`.
+
[source,properties]
----
mp.jwt.verify.publickey.location=https://{yourOktaDomain}/oauth2/default/v1/keys
mp.jwt.verify.issuer=https://{yourOktaDomain}/oauth2/default
----

. Add a `HelloApplication` class in `src/main/java/com/okta/rest` to register your resource and configure JWT authentication: [`h-app`]
+
[source,java]
----
package com.okta.rest;

import com.okta.rest.controller.HelloResource;
import org.eclipse.microprofile.auth.LoginConfig;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.core.Application;
import java.util.Set;

@LoginConfig(authMethod = "MP-JWT")
@ApplicationScoped
public class HelloApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return Set.of(HelloResource.class);
    }
}
----

=== Run and Test Your Helidon API with HTTPie

. Start your app from your IDE or using a terminal:

  mvn package && java -jar ./target/helidon

. Test your API with an access token.

  http Authorization:"Bearer $TOKEN" :8080/hello

=== Build a native Helidon app with GraalVM

. Compile your Helidon app into a native executable using the `native-image` profile:

  mvn package -Pnative-image

. Start your Helidon app:

  ./target/helidon

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

== Startup Time Comparison

. Run each image three times before recording the numbers, then each command five times

. Write each time down, add them up, and divide by five for the average. For example:
+
----
Helidon: (40 + 40 + 39 + 39 + 39) / 5 = 39.4
Micronaut: (36 + 37 + 34 + 34 + 34) / 5 = 35
Quarkus: (19 + 19 + 18 + 19 + 18) / 5 = 18.6
Spring Boot: (53 + 56 + 55 + 55 + 54) / 5 = 54.6
----

.Native Java startup times in milliseconds
|===
|Framework | Command executed | Milliseconds to start

|Helidon | `./helidon/target/helidon` | 39.4
|Micronaut | `./micronaut/target/app` | 35
|Quarkus | `./quarkus/target/quarkus-1.0.0-SNAPSHOT-runner` | 18.6
|Spring Boot | `./spring-boot/target/demo` | 54.6
|===

== Memory Usage Comparison

Test the memory usage in MB of each app using the command below. Make sure to send an HTTP request to each one before measuring.

[source,shell]
----
ps -o pid,rss,command | grep --color <executable> | awk '{$2=int($2/1024)"M";}{ print;}'
----

Substitute `<executable>` as follows:

.Native Java memory used in megabytes
|===
|Framework | Executable | Megabytes before request | Megabytes after request| Megabytes after 5 requests

|Helidon | `helidon` | 44 | 55 | 63
|Micronaut | `app` | 28 | 43 | 54
|Quarkus | `quarkus` | 20 | 31 | 33
|Spring Boot | `demo` | 46 | 57 | 57
|===

IMPORTANT: If you disagree with these numbers and think X framework should be faster, I encourage you to clone https://github.com/oktadev/native-java-examples[the repo] and run these tests yourself. If you get faster startup times for Helidon, do you get faster startup times for Micronaut and Quarkus too?

== Native Java with Helidon FTW!

🚀 Find the code on GitHub: https://github.com/oktadev/native-java-examples[@oktadev/native-java-examples]

👀 Read the blog post: https://developer.okta.com/blog/2022/01/06/native-java-helidon[Build REST APIs and Native Java Apps with Helidon]
