:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

= Build a Secure Java REST API with Quarkus

In this demo, I'll show how to create a secure REST API and native image with Quarkus. You'll see how to run a secure, OAuth 2.0-protected, Java REST API that allows JWT authentication. Then, I'll compare its performance with Micronaut, Spring Boot, and Helidon.

_Check this video's description below for links to its blog post, comments, demo script, and code example._

**Prerequisites:**

- https://sdkman.io/[SDKMAN] (for Java 17 with GraalVM)
- https://httpie.io/[HTTPie] (a better version of cURL)
- An https://developer.okta.com[Okta Developer] Account (or the https://cli.okta.com/[Okta CLI])

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

== Install a JDK with GraalVM

Use SDKMAN to install Java 17 with GraalVM

  sdk install java 22.2.r17-grl

== Generate an OAuth 2.0 Access Token

. Install the https://cli.okta.com/[Okta CLI] and run `okta register` to sign up for a new account. If you already have an account, run `okta login`.

. Run `okta apps create spa`. Set `oidcdebugger` as an app name and press **Enter**.

. Use `\https://oidcdebugger.com/debug` for the Redirect URI and set the Logout Redirect URI to `\https://oidcdebugger.com`.

. Navigate to the https://oidcdebugger.com/[OpenID Connect Debugger website].

.. Fill in your client ID
.. Use `\https://{yourOktaDomain}/oauth2/default/v1/authorize` for the Authorize URI
.. Select **code** for the response type and **Use PKCE**
.. Click **Send Request** to continue

. Set the access token as a `TOKEN` environment variable in a terminal window.

  TOKEN=eyJraWQiOiJYa2pXdjMzTDRBYU1ZSzNGM...

== Create a Quarkus Java REST API

. Use Maven to generate a new Quarkus app with JWT support:
+
[source,shell]
----
mvn io.quarkus:quarkus-maven-plugin:2.12.1.Final:create \
    -DprojectGroupId=com.okta.rest \
    -DprojectArtifactId=quarkus \
    -DclassName="com.okta.rest.quarkus.HelloResource" \
    -Dpath="/hello" \
    -Dextensions="smallrye-jwt,resteasy-reactive"
----

. Edit `src/java/com/okta/rest/quarkus/HelloResource.java` and add user information to the `hello()` method: [`qk-hello`]
+
[source,java]
----
package com.okta.rest.quarkus;

import io.quarkus.security.Authenticated;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.SecurityContext;
import java.security.Principal;

@Path("/hello")
public class HelloResource {

    @GET
    @Authenticated
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@Context SecurityContext context) {
        Principal userPrincipal = context.getUserPrincipal();
        return "Hello, " + userPrincipal.getName() + "!";
    }
}
----

. Add your Okta endpoints to `src/main/resources/application.properties`: [`qk-properties`]
+
[source,properties]
----
mp.jwt.verify.issuer=https://{yourOktaDomain}/oauth2/default
mp.jwt.verify.publickey.location=${mp.jwt.verify.issuer}/v1/keys
----

. Modify the `HelloResourceTest` to expect a 401 instead of a 200:
+
[source,java]
----
package com.okta.rest.quarkus;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;

@QuarkusTest
public class HelloResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
            .when().get("/hello")
            .then()
            .statusCode(401);
    }

}
----

=== Run and Test Your Quarkus REST API with HTTPie

. Run your Quarkus app:

  ./mvnw quarkus:dev

. Test it from another terminal:

  http :8080/hello

. Test with access token:

  http :8080/hello Authorization:"Bearer $TOKEN"

=== Build a Native Quarkus App

. Compile your Quarkus app into a native binary:

  ./mvnw package -Pnative

. Start your Quarkus app:

  ./target/quarkus-1.0.0-SNAPSHOT-runner

. Test it with HTTPie and an access token:

  http :8080/hello Authorization:"Bearer $TOKEN"

== Startup Time Comparison

. Run each image three times before recording the numbers, then each command five times

. Write each time down, add them up, and divide by five for the average. For example:
+
----
Quarkus: (19 + 19 + 20 + 19 + 19) / 5 = 19.2
Micronaut: (18 + 17 + 18 + 21 + 16) / 5 = 18
Spring Boot: (36 + 34 + 42 + 37 + 42) / 5 = 38.2
Helidon: (42 + 42 + 42 + 40 + 42) / 5 = 41.6
----

.Native Java startup times in milliseconds
|===
|Framework | Command executed | Milliseconds to start

|Quarkus | `./quarkus/target/quarkus-1.0.0-SNAPSHOT-runner` | 19.2
|Micronaut | `./micronaut/target/app` | 18
|Spring Boot | `./spring-boot/target/demo` | 38.2
|Helidon | `./helidon/target/helidon` | 41.6
|===

== Memory Usage Comparison

Test the memory usage in MB of each app using the command below. Make sure to send an HTTP request to each one before measuring.

[source,shell]
----
ps -o pid,rss,command | grep --color <executable> | awk '{$2=int($2/1024)"M";}{ print;}'
----

Substitute `<executable>` as follows:

.Native Java memory used in megabytes
|===
|Framework | Executable | Megabytes before request | Megabytes after request| Megabytes after 5 requests

|Quarkus | `quarkus` | 37 | 50 | 52
|Micronaut | `app` | 43 | 59 | 70
|Spring Boot | `demo` | 63 | 75 | 76
|Helidon | `helidon` | 79 | 98 | 133
|===

IMPORTANT: If you disagree with these numbers and think X framework should be faster, I encourage you to clone https://github.com/oktadev/native-java-examples[the repo] and run these tests yourself. If you get faster startup times for Quarkus, do you get faster startup times for Helidon, Micronaut, and Spring Boot too?

== Secure Native Java with Quarkus FTW!

⚡️ Create a secure REST API with Quarkus: `okta start quarkus`

🚀 Find this example's code on GitHub: https://github.com/oktadev/native-java-examples/tree/main/quarkus[@oktadev/native-java-examples/quarkus]

👀 Read the blog post: https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison[Build Native Java Apps with Micronaut, Quarkus, and Spring Boot]
