:experimental:
:commandkey: &#8984;
:toc: macro

= Build a Native Java REST API with Spring Boot and OAuth 2.0

In this demo, I'll show how to create secure REST APIs and native images with Spring Boot. You'll see how to run a secure, OAuth 2.0-protected, Java REST API that allows JWT authentication. Then, I'll compare its performance with Micronaut, Quarkus, and Helidon.

**Prerequisites:**

- https://sdkman.io/[SDKMAN] (for Java 17 with GraalVM)
- https://httpie.io/[HTTPie] (a better version of cURL)
- An https://developer.okta.com[Okta Developer] Account (or the https://cli.okta.com/[Okta CLI])

TIP: The brackets at the end of some steps indicate the IntelliJ Live Templates to use. You can find the template definitions at https://github.com/mraible/idea-live-templates[mraible/idea-live-templates].

toc::[]

== Install a JDK with GraalVM

. Use SDKMAN to install Java 17 with GraalVM

  sdk install java 22.0.0.2.r17-grl

. Add the native extension to the JDK:

  gu install native-image

== Generate an OAuth 2.0 Access Token

. Install the https://cli.okta.com/[Okta CLI] and run `okta register` to sign up for a new account. If you already have an account, run `okta login`.

. Run `okta apps create`. Set `oidcdebugger` as an app name, choose **Single-Page App** and press **Enter**.

. Use `\https://oidcdebugger.com/debug` for the Redirect URI and set the Logout Redirect URI to `\https://oidcdebugger.com`.

. Navigate to the https://oidcdebugger.com/[OpenID Connect Debugger] website. Fill in your client ID, and use `\https://{yourOktaDomain}/oauth2/default/v1/authorize` for the Authorize URI. The `state` field must be filled but can contain any characters. Select **token** for the response type.

. Click **Send Request** to continue.

. Set it as a `TOKEN` environment variable in a terminal window.

  TOKEN=eyJraWQiOiJYa2pXdjMzTDRBYU1ZSzNGM...

== Start a Spring Boot Java API

. Create a Spring Boot app with OAuth 2.0 support:
+
[source,shell]
----
https start.spring.io/starter.zip \
  bootVersion==2.6.6 \
  dependencies==web,oauth2-resource-server,native \
  packageName==com.okta.rest \
  name==spring-boot \
  type==maven-project \
  baseDir==spring-boot | tar -xzvf -
----

. Add a `HelloController` class that returns the user's information: [`sb-hello`]
+
[source,java]
----
package com.okta.rest.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
public class HelloController {

    @GetMapping("/hello")
    public String hello(Principal principal) {
        return "Hello, " + principal.getName() + "!";
    }

}
----

. Configure the app to be an OAuth 2.0 resource server by adding the issuer to `application.properties`.
+
[source,properties]
----
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://{yourOktaDomain}/oauth2/default
----

. Add a `SecurityConfiguration` class to configure JWT authentication: [`securityconfig`]
+
[source,java]
----
package com.okta.rest;

import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer;

@EnableWebSecurity
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests(request -> request.anyRequest().authenticated())
            .oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt);
    }
}
----

=== Run and Test Your Spring Boot API with HTTPie

. Start your app from your IDE or using a terminal:

  ./mvnw spring-boot:run

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

=== Build a Native Spring Boot App

. Compile your Spring Boot app into a native executable using the `native` profile:

  ./mvnw package -Pnative
+
TIP: To build a native app and a Docker container, use the Spring Boot Maven plugin and `./mvnw spring-boot:build-image`.

. Start your Spring Boot app:

  ./target/demo

. Test your API with an access token.

  http :8080/hello Authorization:"Bearer $TOKEN"

== Startup Time Comparison

. Run each image three times before recording the numbers, then each command five times

. Write each time down, add them up, and divide by five for the average. For example:
+
----
Helidon: (40 + 40 + 39 + 39 + 39) / 5 = 39.4
Micronaut: (36 + 37 + 34 + 34 + 34) / 5 = 35
Quarkus: (19 + 19 + 18 + 19 + 18) / 5 = 18.6
Spring Boot: (53 + 56 + 55 + 55 + 54) / 5 = 54.6
----

.Native Java startup times in milliseconds
|===
|Framework | Command executed | Milliseconds to start

|Helidon | `./helidon/target/helidon` | 39.4
|Micronaut | `./micronaut/target/app` | 35
|Quarkus | `./quarkus/target/quarkus-1.0.0-SNAPSHOT-runner` | 18.6
|Spring Boot | `./spring-boot/target/demo` | 54.6
|===

The chart below should help you visualize this comparison.

++++
<script src="https://www.gstatic.com/charts/loader.js"></script>
<div id="startup-times"></div>
<script>
google.charts.load('current', {packages: ['corechart', 'bar']});
google.charts.setOnLoadCallback(drawChart);
function drawChart() {
  var data = google.visualization.arrayToDataTable([
    ['Framework', 'Milliseconds to start', { role: 'style' }],
    ['Helidon', 39.4, 'orange'],
    ['Micronaut', 35, 'blue'],
    ['Quarkus', 18.6, 'red'],
    ['Spring Boot', 54.6, 'green']
  ]);
  var options = {
    title: 'Startup times of native Java frameworks',
    chartArea: {width: '50%'},
    hAxis: {
      title: 'Milliseconds',
      minValue: 0
    },
    vAxis: {
      title: 'Java Framework'
    }
  };
  var chart = new google.visualization.BarChart(document.getElementById('startup-times'));
  chart.draw(data, options);
}
</script>
++++

== Memory Usage Comparison

Test the memory usage in MB of each app using the command below. Make sure to send an HTTP request to each one before measuring.

[source,shell]
----
ps -o pid,rss,command | grep --color <executable> | awk '{$2=int($2/1024)"M";}{ print;}'
----

Substitute `<executable>` as follows:

.Native Java memory used in megabytes
|===
|Framework | Executable | Megabytes before request | Megabytes after request| Megabytes after 5 requests

|Helidon | `helidon` | 44 | 55 | 63
|Micronaut | `app` | 28 | 43 | 54
|Quarkus | `quarkus` | 20 | 31 | 33
|Spring Boot | `demo` | 46 | 57 | 57
|===

++++
<div id="memory-usage"></div>
<script>
google.charts.load('current', {packages: ['corechart', 'bar']});
google.charts.setOnLoadCallback(drawChart);
function drawChart() {
  var data = google.visualization.arrayToDataTable([
    ['Framework', 'Memory usage (MB)', { role: 'style' }],
    ['Helidon', 63, 'orange'],
    ['Micronaut', 54, 'blue'],
    ['Quarkus', 33, 'red'],
    ['Spring Boot', 57, 'green']
  ]);
  var options = {
    title: 'Memory usage of native Java frameworks',
    chartArea: {width: '50%'},
    hAxis: {
      title: 'Megabytes',
      minValue: 0
    },
    vAxis: {
      title: 'Java Framework'
    }
  };
  var chart = new google.visualization.BarChart(document.getElementById('memory-usage'));
  chart.draw(data, options);
}
</script>
++++

IMPORTANT: If you disagree with these numbers and think X framework should be faster, I encourage you to clone https://github.com/oktadev/native-java-examples[the repo] and run these tests yourself. If you get faster startup times for Helidon, do you get faster startup times for Micronaut and Quarkus too?

== Native Java with Spring Boot FTW!

🚀 Find the code on GitHub: https://github.com/oktadev/native-java-examples[@oktadev/native-java-examples]

👀 Read the blog post: https://developer.okta.com/blog/2021/06/18/native-java-framework-comparison[Build Native Java Apps with Micronaut, Quarkus, and Spring Boot]
